import io

from reportlab.lib.pagesizes import A5
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

from .models import Transaction


def generate_receipt_pdf(transaction: Transaction, business_name: str) -> bytes:
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A5)
    width, height = A5
    y = height - 20 * mm

    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width / 2, y, business_name.upper())
    y -= 8 * mm

    c.setFont("Helvetica", 11)
    c.drawCentredString(width / 2, y, "Payment Receipt")
    y -= 10 * mm

    c.line(15 * mm, y, width - 15 * mm, y)
    y -= 8 * mm

    c.setFont("Helvetica", 10)
    c.drawString(15 * mm, y, f"Invoice: {transaction.id[:8].upper()}")
    y -= 6 * mm
    c.drawString(15 * mm, y, f"Date: {transaction.created_at.strftime('%d %b %Y, %I:%M %p')}")
    y -= 6 * mm
    if transaction.customer_name:
        c.drawString(15 * mm, y, f"Customer: {transaction.customer_name}")
        y -= 6 * mm
    y -= 4 * mm

    c.setFont("Helvetica-Bold", 10)
    c.drawString(15 * mm, y, "Payment breakdown:")
    y -= 7 * mm

    c.setFont("Helvetica", 10)
    for part in transaction.parts:
        mark = "PAID" if part.status.value in ("SUCCESS", "MARKED_RECEIVED") else part.status.value
        c.drawString(18 * mm, y, f"Payment {part.part_index}")
        c.drawRightString(width - 15 * mm, y, f"Rs. {part.amount:,.2f}  [{mark}]")
        y -= 6 * mm

    y -= 3 * mm
    c.line(15 * mm, y, width - 15 * mm, y)
    y -= 8 * mm

    c.setFont("Helvetica-Bold", 12)
    c.drawString(15 * mm, y, "Total Paid")
    c.drawRightString(width - 15 * mm, y, f"Rs. {transaction.total_amount:,.2f}")
    y -= 10 * mm

    c.setFont("Helvetica-Oblique", 7)
    c.drawString(
        15 * mm, 15 * mm,
        "Estimated MDR/payment charges shown in-app are informational only and",
    )
    c.drawString(
        15 * mm, 12 * mm,
        "do not guarantee final charges. Generated by SplitPay.",
    )

    c.showPage()
    c.save()
    buf.seek(0)
    return buf.read()


def generate_invoice_number(sequence: int) -> str:
    from datetime import datetime
    year = datetime.utcnow().year
    return f"SP-{year}-{sequence:06d}"
